export const profileIcons = [
  {
    id: 1,
    logo: "/images/users/witcher/logo.png",
    imgPath: [
      "/images/users/witcher/0.png",
      "/images/users/witcher/1.png",
      "/images/users/witcher/2.png",
      "/images/users/witcher/3.png",
      "/images/users/witcher/4.png",
      "/images/users/witcher/5.png",
      "/images/users/witcher/6.png",
      "/images/users/witcher/7.png",
      "/images/users/witcher/8.png",
      "/images/users/witcher/9.png",
      "/images/users/witcher/10.png",
    ],
  },
  {
    id: 2,
    logo: "/images/users/strangerThings/logo.png",
    imgPath: [
      "/images/users/strangerThings/0.png",
      "/images/users/strangerThings/1.png",
      "/images/users/strangerThings/2.png",
      "/images/users/strangerThings/3.png",
      "/images/users/strangerThings/4.png",
      "/images/users/strangerThings/5.png",
      "/images/users/strangerThings/6.png",
      "/images/users/strangerThings/7.png",
      "/images/users/strangerThings/8.png",
      "/images/users/strangerThings/9.png",
      "/images/users/strangerThings/10.png",
      "/images/users/strangerThings/11.png",
      "/images/users/strangerThings/12.png",
      "/images/users/strangerThings/13.png",
      "/images/users/strangerThings/14.png",
      "/images/users/strangerThings/15.png",
    ],
  },
  {
    id:3,
    logo: "/images/users/trollHunters/logo.png",
    imgPath: [
      "/images/users/trollHunters/0.png",
      "/images/users/trollHunters/1.png",
      "/images/users/trollHunters/2.png",
      "/images/users/trollHunters/3.png",
      "/images/users/trollHunters/4.png",
      "/images/users/trollHunters/5.png",
      "/images/users/trollHunters/6.png",
      "/images/users/trollHunters/7.png",
      "/images/users/trollHunters/8.png",
    ],
  },
  {
    id:4,
    logo: "/images/users/sexEducation/logo.png",
    imgPath: [
      "/images/users/sexEducation/0.png",
      "/images/users/sexEducation/1.png",
      "/images/users/sexEducation/2.png",
      "/images/users/sexEducation/3.png",
      "/images/users/sexEducation/4.png",
      "/images/users/sexEducation/5.png",
      "/images/users/sexEducation/6.png",
      "/images/users/sexEducation/7.png",
      "/images/users/sexEducation/8.png",
      "/images/users/sexEducation/9.png",
      "/images/users/sexEducation/10.png",
      "/images/users/sexEducation/11.png",
      "/images/users/sexEducation/12.png",
      "/images/users/sexEducation/13.png",
      "/images/users/sexEducation/14.png",
      "/images/users/sexEducation/15.png",
    ],
  },
  {
    id:5,
    logo: "/images/users/carmenSandiego/logo.png",
    imgPath: [
      "/images/users/carmenSandiego/0.png",
      "/images/users/carmenSandiego/1.png",
      "/images/users/carmenSandiego/2.png",
      "/images/users/carmenSandiego/3.png",
      "/images/users/carmenSandiego/4.png",
      "/images/users/carmenSandiego/5.png",
      "/images/users/carmenSandiego/6.png",
      "/images/users/carmenSandiego/7.png",
      "/images/users/carmenSandiego/8.png",
      "/images/users/carmenSandiego/9.png",
      "/images/users/carmenSandiego/10.png",
      "/images/users/carmenSandiego/11.png",
      "/images/users/carmenSandiego/12.png",
    ],
  },
  {
    id:6,
    logo: "/images/users/moneyHeist/logo.png",
    imgPath: [
      "/images/users/moneyHeist/0.png",
      "/images/users/moneyHeist/1.png",
      "/images/users/moneyHeist/2.png",
      "/images/users/moneyHeist/3.png",
      "/images/users/moneyHeist/4.png",
      "/images/users/moneyHeist/5.png",
      "/images/users/moneyHeist/6.png",
      "/images/users/moneyHeist/7.png",
      "/images/users/moneyHeist/8.png",
      "/images/users/moneyHeist/9.png",
    ],
  },
  {
    id:7,
    logo: "/images/users/arcane/logo.png",
    imgPath: [
      "/images/users/arcane/0.png",
      "/images/users/arcane/1.png",
      "/images/users/arcane/2.png",
      "/images/users/arcane/3.png",
      "/images/users/arcane/4.png",
      "/images/users/arcane/5.png",
      "/images/users/arcane/6.png",
      "/images/users/arcane/7.png",
      "/images/users/arcane/8.png",
      "/images/users/arcane/9.png",
      "/images/users/arcane/10.png",
      "/images/users/arcane/11.png",
    ],
  },
  {
    id:8,
    logo: "/images/users/sacredGames/logo.png",
    imgPath: [
      "/images/users/sacredGames/0.png",
      "/images/users/sacredGames/1.png",
      "/images/users/sacredGames/2.png",
      "/images/users/sacredGames/3.png",
      "/images/users/sacredGames/4.png",
      "/images/users/sacredGames/5.png",
    ],
  },
  {
    id:9,
    logo: "/images/users/bigMouth/logo.png",
    imgPath: [
      "/images/users/bigMouth/0.png",
      "/images/users/bigMouth/1.png",
      "/images/users/bigMouth/2.png",
      "/images/users/bigMouth/3.png",
      "/images/users/bigMouth/4.png",
      "/images/users/bigMouth/5.png",
      "/images/users/bigMouth/6.png",
      "/images/users/bigMouth/7.png",
      "/images/users/bigMouth/8.png",
    ],
  },
  {
    id:10,
    logo: "/images/users/squidGames/logo.png",
    imgPath: [
      "/images/users/squidGames/0.png",
      "/images/users/squidGames/1.png",
      "/images/users/squidGames/2.png",
      "/images/users/squidGames/3.png",
      "/images/users/squidGames/4.png",
      "/images/users/squidGames/5.png",
      "/images/users/squidGames/6.png",
      "/images/users/squidGames/7.png",
      "/images/users/squidGames/8.png",
      "/images/users/squidGames/9.png",
      "/images/users/squidGames/10.png",
      "/images/users/squidGames/11.png",
      "/images/users/squidGames/12.png",
      "/images/users/squidGames/13.png",
    ],
  },
  {
    id:11,
    logo: "/images/users/theDragonPrince/logo.png",
    imgPath: [
      "/images/users/theDragonPrince/0.png",
      "/images/users/theDragonPrince/1.png",
      "/images/users/theDragonPrince/2.png",
      "/images/users/theDragonPrince/3.png",
      "/images/users/theDragonPrince/4.png",
      "/images/users/theDragonPrince/5.png",
      "/images/users/theDragonPrince/6.png",
      "/images/users/theDragonPrince/7.png",
      "/images/users/theDragonPrince/8.png",
      "/images/users/theDragonPrince/9.png",
      "/images/users/theDragonPrince/10.png",
      "/images/users/theDragonPrince/11.png",
    ],
  },
];
    
